language: node_js
node_js:
  - "8"
cache: npm
notifications:
  email: false
script:
  - commitlint-travis
  - npm run lint
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run semantic-release
